events {}

http {
    log_format soc_format '$remote_addr - $remote_user [$time_local] '
                          '"$request" $status $body_bytes_sent '
                          '"$http_referer" "$http_user_agent"';

    access_log /var/log/nginx/access.log soc_format;
    error_log  /var/log/nginx/error.log warn;

    server {
        listen 80;

        location / {
            proxy_pass http://dvwa:80;
            proxy_set_header Host $"dvwa";
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
